### ISSUE TITLE
guided demo problem 

### ISSUE THREAD

**Issue by terrychenism** [jrosebr1/bat-country#1]
Hi, I just test the  Vincent van Gogh’s Wheat Field image guided using Warhol’s Marilyn Monroe. Which  end_layer do you use? I have try to use  inception_3a/output ~ inception_4e/output and those cannot generate the image that you posted on http://www.pyimagesearch.com/2015/07/13/generating-art-with-guided-deep-dreaming/   Thanks.

**Comment by terrychenism** [comment]
I figured it out. Thanks.

**Comment by jrosebr1** [comment]
No problem, glad it worked for you.
