### ISSUE TITLE
make a command line interface for this

### ISSUE THREAD

**Issue by jtoy** [jrosebr1/bat-country#4]
I love the project, can we get a command line interface to it? or if you are open to it, I or someone else can write it.

**Comment by jrosebr1** [comment]
What type of CLI are you thinking of? What is the desired functionality?

**Comment by jtoy** [comment]
Well, you do have the demo app. So that is similar.   I was thinking of an official command line.

**Comment by jrosebr1** [comment]
What do you mean by "an official command line"? You mean an interface that prompts you for inputs? If so, I think using command line switches is just as easy and more portable.

**Comment by jrosebr1** [comment]
Since there haven't been any comments on this, I'm going to close this issue.
