### ISSUE TITLE
PIP install bat-country Breaks tensorflow in virtualenv

### ISSUE THREAD

**Issue by janislejins** [jrosebr1/bat-country#5]
## issue

Bat-country dependancies are out of date - thus when I ran
`pip install bat-country`
I got errors when you try to run tensorflow in same env because you have just downgraded all the packages... incl protobuf.
## work around

```
pip uninstall bat-country
pip install --upgrade (all packages that just got downgraded) 
or 
pip install tensorflow (*should* upgrade everything that needs upgrading)
```

I uninstalled bat-country then re-upgraded the relevant tensorflow packages everything worked again.
then

```
git clone https://github.com/jrosebr1/bat-country.git
python setup.py install
```

and it should work...

**Comment by jrosebr1** [comment]
Thanks for mentioning this. Another solution would be to create a separate Python virtual environment strictly for bat-country, that way you don't have to worry about upgrading/downgrading any packages you already have installed.

**Comment by jrosebr1** [comment]
@janislejins Were you able to resolve the issue by creating a separate virtual environment and then installing the dependencies there? If so, let me know and I'll close the issue. Otherwise, I'll come up with a solution.

**Comment by janislejins** [comment]
yeah all good. Close the issue.

On Tue, May 3, 2016 at 9:09 PM, Adrian Rosebrock notifications@github.com
wrote:

> @janislejins https://github.com/janislejins Were you able to resolve
> the issue by creating a separate virtual environment and then installing
> the dependencies there? If so, let me know and I'll close the issue.
> Otherwise, I'll come up with a solution.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jrosebr1/bat-country/issues/5#issuecomment-216497444

## 

http://www.janislejins.com/

Janis Lejins
janis@janislejins.com / +61408283062

www.janislejins.com

[image: Twitter]  https://twitter.com/jlejins [image: Facebook]
https://www.facebook.com/janislejins [image: LinkedIn]
https://www.linkedin.com/in/lejins [image: Instagram]
http://instagram.com/janislejins [image: Github]
http://github.com/janislejins
